var app = new Vue({
	el: '#cyberapp',
	methods:{
		addLike(){
			this.readervotes +=1;
			this.readerlikes +=1;
		},
		addDislike(){
			this.readervotes +=1
		},
		selectViewTitle(index){
			this.viewTitle = index
			console.log(index);
		}
	},
	computed:{
		readerResp(){
			return (this.readerlikes / this.readervotes) *100
		},
		viewTitleName(){
			return this.titles[this.viewTitle].name
		},
		viewTitleRank(){
			return this.titles[this.viewTitle].rank
		},
		viewTitleYear(){
			return this.titles[this.viewTitle].year
		},
		viewTitleDirector(){
			return this.titles[this.viewTitle].director
		},
		viewTitleScreenplay(){
			return this.titles[this.viewTitle].screenplay
		},
		viewTitleTime(){
			return this.titles[this.viewTitle].time
		},
		viewTitlePoster(){
			return ('./assets/imgs/posters/'+this.titles[this.viewTitle].poster)
		},
		
	},
	data: {	
				viewTitle:0,
				lang: 'English',
				format: 'Motion Picture',
				tomato: '93%',
				siscore: 99,
				cyscore: 99,
				funscore: 80,
				readervotes: 5,
				readerlikes: 4,
				flag: false,
				summary: 'Boy meets replicant, boy kills other replicant, boy may be replicant?',
				review: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
				poster: 'bladerunner.jpeg',
				titles: [
					{
						name:'Blade Runner', 
						rank: 01,
						year: '1982',
						director: 'Ridley Scott',
						screenplay: 'Philip K. Dick, Hampton Fancher, David Peoples',
						source: 'Short Story Do Androids Deram of Electric Sheep by Philp K. Dick',
						cast: ['Harrison Ford', 'Rutger Hoawrd', 'Sean Young','Daryl Hanna'],
						time: '110m',
						lang: 'English',
						format: 'Motion Picture',
						tomato: '93%',
						siscore: 99,
						cyscore: 99,
						funscore: 80,
						readervotes: 5,
						readerlikes: 4,
						flag: false,
						summary: 'Boy meets replicant, boy kills other replicant, boy may be replicant?',
						review: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'bladerunner.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Akira', 
						rank: 02,
						year: '1988',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: 'Manga by ',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Max Headroom 20m into the future', 
						rank: 03,
						year: '1985',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'12 Moknkeys', 
						rank: 04,
						year: '1995',
						director: 'Terry Gilliam',
						screenplay: 'Alain Smithee',
						source: 'La Jitee, by Chris Marker',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Robocop',
						rank: 05, 
						year: '1987',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Terminator', 
						rank: 06,
						year: '1984',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Stange Days', 
						rank: 07,
						year: '1995',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Ghost in the Shell', 
						rank: 08,
						year: '1993',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Blade Runner 2049', 
						rank: 09,
						year: '2018',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Total Recal', 
						rank: 10,
						year: '1980',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Alphaville', 
						rank: 11,
						year: '1967',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Altered Carbon', 
						rank: 12,
						year: '2018',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Chappie', 
						rank: 13,
						year: '2015',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Ready Palyer One', 
						rank: 14,
						year: '2018',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Jonny Mnemonic',
						rank: 15, 
						year: '1995',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Aeon Flux', 
						year: '1991',
						rank: 16, 
						year: '1991',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Hardware',
						rank: 17, 
						year: '1990',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Children of Men', 
						rank: 18,
						year: '2006',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Elysium', 
						rank: 19,
						year: '2013',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Minortiy Report', 
						rank: 20,
						year: '2002',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'AI', 
						rank: 21,
						year: '2001',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'District 9', 
						rank: 22,
						year: '2009',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'Demolition Man', 
						rank: 23,
						year: '1993',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					},
					{
						name:'FreeJack', 
						rank: 24,
						year: '1992',
						director: 'Alain Smithee',
						screenplay: 'Alain Smithee',
						source: '',
						cast: ['John Doe', 'Jane Doe', 'James Doe'],
						time: '',
						lang: 'deafult',
						format: 'deafult',
						tomato: 0,
						siscore: 0,
						cyscore: 0,
						funscore: 0,
						readervotes: 0,
						readerlikes: 0,
						flag: false,
						summary: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
						review: 'Libero velit, impedit aliquam a, ipsum in reiciendis cum corrupti vero nulla minima nobis totam, possimus tempora delectus. Perspiciatis sint accusantium hic.',
						poster: 'default.jpeg',
						screens: [],
						links:[]
					}
				]
			}
})

